name: zip

on:
  push:

jobs:
  zip:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/upload-artifact@v3
        with:
          name: test
          path: files/
